/* CVS $Id: $ */
package ca.uqam.vocabulary.model; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/heon/01-SPRINT/2021-05-17-SPRINT-06/00-GIT/CCRD-CRDC/src/main/resources/00-crdc-ccdr-vocabulary/crdc-ccrd-semantic.ttl 
 * @author Auto-generated by schemagen on 27 juil. 2021 10:11 
 */
public class CRDC_CCRD {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();
    public static final String CRDC_CCRD_VOCABULARY = "http://purl.org/uqam.ca/vocabulary/crdc-ccrd";
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = CRDC_CCRD_VOCABULARY+"#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Author: Michel Héon PhD : heon.michel@uqam.ca";
    
    public static final Property classDefinition = M_MODEL.createProperty( NS + "classDefinition" );
    
    public static final Property classTitle = M_MODEL.createProperty( NS + "classTitle" );
    
    public static final Property elementDescription = M_MODEL.createProperty( NS + "elementDescription" );
    
    public static final Property elementLabel = M_MODEL.createProperty( NS + "elementLabel" );
    
    public static final Property elementTypeLabel = M_MODEL.createProperty( NS + "elementTypeLabel" );
    
    public static final Property hasHierarchicalStructure = M_MODEL.createProperty( NS + "hasHierarchicalStructure" );
    
    public static final Property hasID = M_MODEL.createProperty( NS + "hasID" );
    
    public static final Property hasLevel = M_MODEL.createProperty( NS + "hasLevel" );
    
    public static final Resource CRDC_CCRD_Class = M_MODEL.createResource( NS + "CRDC_CCRD_Class" );
    
    public static final Resource CRDC_CCRD_Division = M_MODEL.createResource( NS + "CRDC_CCRD_Division" );
    
    public static final Resource CRDC_CCRD_Group = M_MODEL.createResource( NS + "CRDC_CCRD_Group" );
    
    public static final Resource CRDC_CCRD_SubClass = M_MODEL.createResource( NS + "CRDC_CCRD_SubClass" );
    
    public static final Resource Category = M_MODEL.createResource( NS + "Category" );
    
    public static final Resource Entity = M_MODEL.createResource( NS + "Entity" );
    
    /** <p>This piece of the CRDC allows R&amp;D activity to be categorized or classified 
     *  according to the field of research (FOR); it is the methodology used in the 
     *  R&amp;D that is being considered. The categories within this classification 
     *  include major fields of research based on the knowledge sources, the objects 
     *  of interest, and the methods and techniques being used.Cette partie de la 
     *  CCRD permet de catégoriser ou de classer les activités de R-D selon le domaine 
     *  de recherche; c'est la méthodologie utilisée dans la R-D qui est prise en 
     *  considération. Les catégories de cette classification comprennent les principaux 
     *  domaines ou domaines de recherche selon les sources de connaissances, les 
     *  objets et les méthodes et techniques utilisées.</p>
     */
    public static final Resource FOR_DDR_Entity = M_MODEL.createResource( NS + "FOR_DDR_Entity" );
    
    /** <p>Cette classification permet la catégorisation de la R-D selon le but ou le 
     *  résultat de cette activité perçu par le fournisseur de données (chercheur). 
     *  Il s'agit de domaines économiques, sociaux, technologiques ou scientifiques 
     *  distincts permettant de définir les buts principaux de la R-D. Les attributs 
     *  appliqués à la conception de la classification selon l'objectif socioéconomique 
     *  comprennent une combinaison d'industries, de processus, de produits et d'éléments 
     *  de santé, d'éducation, de culture, d'éthique et autres volets socioenvironnementaux 
     *  d'intérêt particulier.This classification allows the categorization of R&amp;D 
     *  according to the purpose or outcome of the R&amp;D as perceived by the data 
     *  provider (researcher). It consists of discrete economic, social, technological 
     *  or scientific domains for identifying the principal purposes of the R&amp;D. 
     *  The attributes applied to the design of the SEO classification comprise a 
     *  combination of industries, processes, products, health, education, culture, 
     *  ethics and other social and environmental aspects of particular interest.</p>
     */
    public static final Resource SEO_OSE_Entity = M_MODEL.createResource( NS + "SEO_OSE_Entity" );
    
    /** <p>This classification allows R&amp;D activity to be categorized according to 
     *  the type of research effort, namely basic or fundamental research (which groups 
     *  pure basic research and strategic basic research other split in the Frascati 
     *  Manual 2015), applied research and experimental development.Cette classification 
     *  permet de catégoriser les activités de R-D en fonction du type d'effort de 
     *  recherche, à savoir la recherche fondamentale (qui regroupe la recherche fondamentale 
     *  pure et la recherche fondamentale stratégique, par ailleurs divisées dans 
     *  le Manuel de Frascati 2015), la recherche appliquée et le développement expérimental.</p>
     */
    public static final Resource TOA_TDA_Entity = M_MODEL.createResource( NS + "TOA_TDA_Entity" );
    
}
